spring.application.name=customer-service
server.port=8082

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs

# Configuración de BD H2 para Órdenes
spring.datasource.url=jdbc:h2:mem:orderdb
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true