DROP TABLE IF EXISTS employees;

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(100),
    middleName VARCHAR(100),
    lastName VARCHAR(100),
    secondLastName VARCHAR(100),
    email VARCHAR(50) UNIQUE NOT NULL,        
    phone VARCHAR(20),
    adress VARCHAR(255), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active TINYINT DEFAULT 1 CHECK (is_active IN (0, 1))
);