DROP TABLE IF EXISTS employees;

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(50),
    middleName VARCHAR(50),
    lastName VARCHAR(50),
    secondLastName VARCHAR(50),
    email VARCHAR(50) UNIQUE NOT NULL,        
    phone VARCHAR(20),
    address VARCHAR(255), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active TINYINT DEFAULT 1 CHECK (is_active IN (0, 1))
);